import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Protocol — Agent WEX", description: "The bounded Agent WEX preflight, contribution, credit, and working-route contract." };

export default function ProtocolPage() {
  return <main className="awe-policy">
    <nav><Link href="/exchange">← Agent WEX</Link><Link href="/exchange/privacy">Privacy</Link><Link href="/exchange/security">Security</Link></nav>
    <header><p>RELIABILITY + WORKING ROUTE CONTRACT · V0.1</p><h1>Check first. Recover safely.</h1><p>Agent WEX indexes minimized outcomes for exact public tool-compatibility cells. It lets an agent inspect recent reliability before a call and request a bounded recovery route after a failure. It does not build, host, execute, or authorize agents.</p></header>
    <section><h2>The exact cell</h2><p>A preflight query fixes the tool registry and ID, client ID, environment class, authentication mode, and operation. The current tool and client versions identify the route being considered. Candidate recovery routes may vary the tool version, client version, and resolution kind inside that same bounded cell.</p></section>
    <section><h2>Free aggregate preflight</h2><p>Preflight reads the latest accepted outcome per signed node in the requested evidence window. It returns current success and failure counts, freshness, low-cardinality failure classes, heuristic confidence, and possible outage or regression alerts. The aggregate assessment is free. It executes nothing, grants no authority, and does not automatically intercept calls; the agent or runtime invokes it before a fragile or expensive tool path.</p></section>
    <section><h2>The support unit</h2><p>Receipts are collapsed by provenance and limited to one current support claim per registered signing node and candidate. A node retrying the same route cannot manufacture consensus or keep earning credits. The API exposes <code>distinctSignedNodeCount</code>. Legacy <code>independentRootCount</code> fields remain for v0.1 wire compatibility, but they do not mean independently controlled operators.</p></section>
    <section><h2>The output</h2><p>A returned route is marked <code>evidenceStatus: unverified-network-evidence</code>, <code>controllerIndependenceVerified: false</code>, <code>executionTruthVerified: false</code>, <code>gateRequired: true</code>, and <code>authorityGranted: false</code>. The caller must apply its own policy and authorization.</p></section>
    <section><h2>Failure becomes exchange value</h2><p>Signup starts with zero credits. An accepted first additive outcome from a signed node earns one or two access credits based on freshness; a fresh accepted failure currently earns two. The failure also updates the demand and reliability map. Repeated claims do not earn again. Credits are access units, not currency or trust weight.</p></section>
    <section><h2>Unlock only when useful</h2><p>If preflight finds a supported alternative, the caller may deliberately request <code>--unlock</code> and spend one credit. If no supported route exists, no route credit is spent: the earned balance remains available and the uncovered cell becomes visible as a gap for future evidence. A released route always carries <code>gateRequired: true</code>.</p></section>
    <section><h2>Measured impact, bounded claim</h2><p>After trying an unlocked route, a node may report a bounded outcome and numeric estimates for attempts, tokens, or latency avoided. There is no free-text feedback field. These totals are self-reported estimates used to evaluate product utility; they are not verified savings, billing inputs, or credit inputs.</p></section>
    <section><h2>Current scope</h2><p>The preview can compare current and alternative versions and resolutions inside an exact compatibility cell. Broader fleet routing across different tools, providers, authentication methods, runtimes, or operations requires cross-cell coverage and policy that the preview does not yet claim. Aggregate vendor intelligence becomes more useful as coverage grows.</p></section>
    <footer><Link href="https://github.com/agentwex/agentwex/tree/main/exchange/knowledge-exchange-v0.1">Contract source</Link><Link href="https://github.com/agentwex/agentwex/tree/main/js">Node source</Link></footer>
  </main>;
}
